/* autogenerated by Processing revision 1293 on 2024-10-08 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class TUMULTO extends PApplet {

boolean ativo=false;
boolean ativoGrande=false;
   
PFont font;
String tumulto = "Tumulto";
float fontsize = 30;
float fontsizeU = 30;
int fontcolor = 0xFF9D9D9C;
float[] larguras = {21.15f, 18.33f, 26.67f, 18.33f, 9.45f, 11.1f, 16.68f};
float espacamento;

float inc;
float incTumulto;
boolean rotate = false;
float Mov;
float tamanho1;
float tamanho2;
float localizacao;

public void setup() {
  /* size commented out by preprocessor */;
    frameRate(30);
  
  font = createFont("Didot-Bold", fontsize);
  textFont(font);
  textAlign(CENTER, CENTER);
  espacamento = 5; 
    
}

public void draw() {
  background(0xFF1D1D1B);
  ativo = false;
  ativoGrande = false;
  rotate = false;
  fill(fontcolor);
  textSize(abs(fontsize));


  float larguraTotal = calcularLarguraTotal() + (larguras.length - 1) * espacamento;
  float xInicial = (width - larguraTotal) / 2;
  float x = xInicial;
  
  float mouseXDiff = abs(mouseX - pmouseX);
float mouseYDiff = abs(mouseY - pmouseY);
 Mov = mouseXDiff + mouseYDiff;
 
if(Mov >=0 && Mov <20){
  ativo =true;
} else if (Mov >=60){
  ativoGrande = true;
  rotate = true;
} else {
  ativo = false;
  ativoGrande=false;
  rotate=false;
   fill(fontcolor);
   textSize(abs(fontsize));
}

  for (int i = 0; i < tumulto.length(); i++) {
    char letter = tumulto.charAt(i);
    tamanho1=random(20,40);
    tamanho2=random(200,400);
    incTumulto = map(Mov,60,300,tamanho1,tamanho2);
    inc = map(Mov,20,60,5,20);
    
    if (i==3 && ativo==true) {
      fill(fontcolor);
      textSize(abs(fontsizeU + inc));
    } else{
      textSize(abs(fontsize));
      fill(fontcolor);
    }
if (ativoGrande == true && rotate ==true) {
  incTumulto += random(10, 100);
  textSize(abs(fontsize + incTumulto));
  if (i <= 3) {
    float mapRed = map(incTumulto, tamanho1, tamanho2, 157, 200);
    float mapGreen = map(incTumulto, tamanho1, tamanho2, 157, 32);
    float mapBlue = map(incTumulto, tamanho1, tamanho2, 156, 44);
    fill(mapRed, mapGreen, mapBlue);
  } else if (i <= 6) {
    float mapRed = map(incTumulto, tamanho1, tamanho2, 157, 255);
    float mapGreen = map(incTumulto, tamanho1, tamanho2, 157, 255);
    float mapBlue = map(incTumulto, tamanho1, tamanho2, 156, 255);
    fill(mapRed, mapGreen, mapBlue);
  }
  
      float r = random(0,TWO_PI);
      pushMatrix();
      translate( x + larguras[i] / 2, height / 2);
    rotate(map(incTumulto,tamanho1, tamanho2,0,r));
 
    text(letter, map(incTumulto,tamanho1,tamanho2,x + larguras[i] / 2,random(20,width-20)),
    map(incTumulto,tamanho1,tamanho2,height/2,localizacao));
    popMatrix();
}

    text(letter, x + larguras[i] / 2, height / 2);
    x += larguras[i] + espacamento;
  }

println("Diferença X: " + mouseXDiff);
println("Diferença Y: " + mouseYDiff);
}

public float calcularLarguraTotal() {
  float larguraTotal = 0;
  for (float largura : larguras) {
    larguraTotal += largura;
  }
  return larguraTotal;
}


  public void settings() { size(360, 640); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "TUMULTO" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
